title: MrAliNp
desciption: >
  Welcome to my personal website
email: alinaderiparizi@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alinaderiparizi.ir" # the base hostname & protocol for your site
twitter_username: mralinp
github_username:  mralinp
github: https://github.com/mralinp/mralinp.github.io/

markdown: kramdown
page_excerpts: true
favicon: "https://avatars.githubusercontent.com/u/19627147?v=4"
collections:
  posts:
    permalink: "/blog/:title:output_ext"
    output: true
defaults:
- scope:
    path: _posts
    type: posts
- scope:
    path: ''
  values:
    image: "https://avatars.githubusercontent.com/u/19627147?v=4"
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-redirect-from
- jemoji
- jekyll-paginate

paginate: 5
paginate_path: "/blog/page-:num/"
