scholar: "https://scholar.google.com/citations?user=2zycrawAAAAJ&hl=en"
orcid: "https://orcid.org/0009-0004-6491-8950"
orcid_id: "0009-0004-6491-8950"
semantic_scholar: "https://www.semanticscholar.org/author/2385183618"
semantic_scholar_id: "2385183618"
github: "https://github.com/mralinp"
linkedin: "https://www.linkedin.com/in/ali-naderi-parizi-5a0a74107/"
twitter: "https://twitter.com/alinaderiparizi"
email: "me@alinaderiparizi.com"
cv: "/assets/resume/ali-naderi-parizi-cv.pdf"
